Added exceptionhandling for QSOs with no Call
wavelog/wavelog pull request #1029
Opened 2024-10-01 18:31 UTC by int2001

Sometimes a Logbook-Tool called "HamOffice" exports wrong ADIFs.
There are QSOs without a partner. This one fixes the issue (QSOs will be skipped during import)

2024-10-01 18:58 UTC, AndreasK79 commented
ADIF importer works with this fix. Can't really test the rest.

2024-10-03 13:04 UTC, HB9HIL requested changes
just some minor things

2024-10-03 13:06 UTC, int2001 commented on application/models/Logbook_model.php
> +			log_message("Error","Trying to import QSO without Call for station_id ".$station_id);
Good idea. I like

2024-10-03 13:14 UTC, HB9HIL approved these changes

2024-10-03 13:41 UTC, merged