[QSLPrint] Added export button for selected QSOs
wavelog/wavelog pull request #1123
Opened 2024-10-23 18:45 UTC by AndreasK79

![image](https://github.com/user-attachments/assets/671037ed-3b92-4028-b545-a932a7beef17)
Added another button for exporting selected QSOs.
Changed wording from printed to sent on another button.

2024-10-26 06:37 UTC, HB9HIL requested changes

2024-10-26 06:37 UTC, HB9HIL commented on application/views/qslprint/qslprint.php
> +</script>
Let us move this to the footer.php so we can reuse this :)

2024-10-26 06:50 UTC, HB9HIL commented on application/views/qslprint/qslprint.php
> +</script>
I just noticed we already have a variable for this in the footer :)

```suggestion
```

2024-10-26 06:52 UTC, HB9HIL commented on assets/js/sections/qslprint.js
> +			const filename = `${user_callsign}-${year}${month}${day}-${hours}${minutes}.adi`;
```suggestion
			const filename = `${my_call}-${year}${month}${day}-${hours}${minutes}.adi`;
```

2024-10-26 06:55 UTC, HB9HIL requested changes
the user_callsign from the session is already global available as `my_call` 
See footer.php Line 25

2024-10-26 08:31 UTC, AndreasK79 commented
> the user_callsign from the session is already global available as `my_call` See footer.php Line 25

Thanks. I didn't look closely enough :)

2024-10-26 17:16 UTC, HB9HIL approved these changes

2024-10-26 17:21 UTC, merged

2024-10-27 21:34 UTC, m0urs commented
Thank you very much!