[WIP] - Antenna Path
wavelog/wavelog pull request #1165
Opened 2024-11-05 09:44 UTC by HB9HIL

Since we have Antenna Path in the Database, supporting it also in ADIF, we should calculate distances based that. 

This PR includes several place where this is relevant. Also Maps.

Working together with @AndreasK79 on this over a time.

2024-11-18 19:45 UTC, HB9HIL commented
@AndreasK79 I tried to implement the longpath pathlines in the staticmap.. Quiet complex so let's address maps (staticmap and lba) in another PR on another day

2024-11-20 12:27 UTC, phl0 requested changes
Code works fine on my end show shows distance for LP correct upon logging and in the database. The QSO dislpay however shows the SP value:

![image](https://github.com/user-attachments/assets/301fb695-97bb-4d76-8314-f111e6a9c07b)

IMHO this should be corrected.

2024-11-20 12:30 UTC, phl0 requested changes

2024-11-20 12:30 UTC, phl0 commented on application/views/view_log/qso.php
> +                                    log_message('error', 'Ant Path: '.$ant_path);
Debug message to be removed?!

2024-11-20 12:38 UTC, phl0 requested changes
Changing the ANT_PATH in QSO edit does not trigger a re-calculation of distance. Logged a LP QSO with HB9HIL and changed ANT_PATH to SP in QSO edit results in:

![image](https://github.com/user-attachments/assets/c2e9c56a-b22e-4d29-bffe-c59779c90478)

2024-11-20 15:05 UTC, HB9HIL commented
> Changing the ANT_PATH in QSO edit does not trigger a re-calculation of distance. Logged a LP QSO with HB9HIL and changed ANT_PATH to SP in QSO edit results in:

should be fixed. Please test agn

2024-11-20 15:06 UTC, HB9HIL commented
QRX. There is a bad interfering when calling the edit ajax in QSO view due to identical ID's

2024-11-20 20:11 UTC, phl0 approved these changes
Edit QSO works fine now and switches SP/LP as desired. Good to merge imho.

2024-11-20 22:37 UTC, merged