Previous QSL Check
wavelog/wavelog pull request #1353
Opened 2024-12-14 09:44 UTC by HB9HIL

<img width="277" alt="image" src="https://github.com/user-attachments/assets/dc69a2c2-ea48-4a77-aac5-550b822f4d34" />

Show an additional column in the QSL queue which shows if there were already sent QSL cards on the same band/mode (or if not empty sat_name) to that station.

2024-12-14 10:00 UTC, int2001 requested changes

2024-12-14 10:00 UTC, int2001 commented on application/models/Qslprint_model.php
> +			AND (" . implode(' OR ', $where) . ")
station_id is missing. this one checks every QSO in the instance

2024-12-14 11:49 UTC, AndreasK79 commented
@HB9HIL you must fix when lines are added to the table as well:
![image](https://github.com/user-attachments/assets/6fdf1660-1409-498a-9ee8-d1559afeddfe)
Click on QSO list, and add a QSO. It will then look like the picture.

2024-12-16 11:24 UTC, int2001 approved these changes
works now as expected and shows the amount of already sent QSLs for:
- same call
- on same band and mode
- on same SAT (if SAT-QSO)
- out of same station-location

2024-12-16 11:58 UTC, AndreasK79 commented
Javascript still needs to be fixed when adding lines.

2024-12-16 12:08 UTC, HB9HIL commented
> Javascript still needs to be fixed when adding lines (just a reminder).

yep I know. working on it later that day

2024-12-19 12:10 UTC, HB9HIL commented
> Javascript still needs to be fixed when adding lines (just a reminder).

fixed

2024-12-20 12:40 UTC, AndreasK79 commented
Errors gone, merge time :)

2024-12-20 12:40 UTC, AndreasK79 approved these changes

2024-12-20 12:48 UTC, merged