[WIP]: Use cURL for LoTW download to be able to catch errors
wavelog/wavelog pull request #368
Opened 2024-05-16 16:30 UTC by phl0

Use cURL for LoTW downloads so that we are able to catch errors. WIP as this needs to be verified once LoTW is back online.

2024-05-16 16:31 UTC, phl0 commented
In case of errors during download it should look like this:

![Screenshot from 2024-05-16 18-30-36](https://github.com/wavelog/wavelog/assets/7112907/e64fb8f8-3105-4805-bdde-e37b2d883249)

2024-05-17 14:37 UTC, phl0 commented
Just tested with a locally provided LoTW report file. Working fine so far. So undrafting here.

2024-05-18 15:59 UTC, int2001 requested changes
it still leaks lotw-credentials to the log (perhaps a try/catch can solve it)
But: Good improvement. One more piece of code, where we get rid of fopen.

Needs to be tested again when lotw is back online

2024-05-18 16:00 UTC, phl0 commented
I will have a look if I can get it to *not* spit credentials to log or GUI. Tnx

2024-05-20 08:18 UTC, int2001 approved these changes

2024-05-20 14:14 UTC, merged