Add filter for contests
wavelog/wavelog pull request #512
Opened 2024-06-28 19:25 UTC by derFogel

As the title says. This adds a filter for the advanced logbook that allows you to search by contest.

I know translations are missing, but I don't know how to create them.

2024-06-28 19:35 UTC, HB9HIL commented
Hello @derFogel 

For Information how we translate things in Wavelog you can refer to this Wiki:
https://github.com/wavelog/wavelog/wiki/Translations

Use `__("Contest")` 

not `lang('gen_hamradio_contest')`


You don't have to do more. The translation process takes care of the rest.

2024-06-28 20:07 UTC, HB9HIL commented on application/views/logbookadvanced/index.php
> +                         <label class="form-label" for="contest"><?php echo lang('gen_hamradio_contest'); ?></label>
```suggestion
                         <label class="form-label" for="contest"><?= __("Contest"); ?></label>
```

2024-06-28 20:08 UTC, HB9HIL requested changes
@AndreasK79 should check this aswell. Please change this line as mentioned.

2024-06-28 20:16 UTC, AndreasK79 commented
I had plans for adding this filter, however with a dropdown with contests from the database, so that you don't have use free text to search. I believe that would be a better approach.

2024-06-28 20:22 UTC, AndreasK79 commented
Just to add to it, I see you use wildcard and like in the query, so perhaps this is sufficient. 
Any objections to contest filtering this way @int2001 and @phl0 ?

2024-06-28 20:31 UTC, HB9HIL commented
> I had plans for adding this filter, however with a dropdown with contests from the database, so that you don't have use free text to search. I believe that would be a better approach.

Maybe just contests which appear at least once in QSO table?

2024-07-03 06:22 UTC, AndreasK79 commented
I found another problem with this approach. Since the Advanced Logbook uses the existing contest table, a contest from that table needs to be set, to be displayed in the table, If not, the column will be blank.

In other words, if you batch edit qsos and set a contest that is not in this table, it will be a problem.

I think the solution would be to use a dropdown filled from the existing contest table.

2024-07-03 06:29 UTC, int2001 commented
> I think the solution would be to use a dropdown filled from the existing contest table.

... which will cause a problem if the Op imports ADIFs with contests which aren't at that table.
A full-scan on every LBA-Load (for filling the dropdown with distinct contest-ids) can also not be the solution. it'll slow down everything in extreme (doesn't scale on huge logbooks).

perhaps someone has an idea to solve this problem.

2024-07-05 23:20 UTC, derFogel commented
I fixed a bug, were sometimes the map/globe wasn't showing the stations.

I like the idea with the dropdown. To deal the problem of missing contest ids, there could be an option in the admin menu to create missing contests from the qso database.

2024-07-14 10:01 UTC, AndreasK79 approved these changes

2024-07-14 10:01 UTC, HB9HIL approved these changes
Fine with me now

2024-07-14 11:11 UTC, phl0 approved these changes
Works fine for me.

2024-07-14 11:24 UTC, AndreasK79 commented
@derFogel we did some small modifications, but agreed on it in the end. Merge time :)

2024-07-14 11:24 UTC, merged