Label mark
wavelog/wavelog pull request #572
Opened 2024-07-12 05:46 UTC by int2001

Added the ability to mark QSLs as sent/printed within the printing Dialog, to save a few clicks.

<img width="498" alt="image" src="https://github.com/user-attachments/assets/23adf617-d51a-492f-9f9c-ad5cb570c061">

2024-07-13 12:12 UTC, phl0 requested changes
IMHO we need a hint here. I made the mistake to mark as printed and then wanted to hit print. But the QSOs are marked as printed already. Maybe lock the mark button until print is pressed? Or add a text hint?

2024-07-13 17:33 UTC, AndreasK79 approved these changes

2024-07-13 18:20 UTC, phl0 approved these changes
This looks fine to me now. :)

2024-07-13 18:57 UTC, HB9HIL approved these changes

2024-07-14 09:38 UTC, phl0 approved these changes
Also fine with me. Tested and works.

2024-07-14 10:28 UTC, merged