DXCC Multiselect - Scroll on Mobile does not work
wavelog/wavelog pull request #765
Opened 2024-08-17 07:26 UTC by HB9HIL

This is a difficult one. This issue is known at the source repo -> https://github.com/davidstutz/bootstrap-multiselect/issues/1233

There are various possible solutions. The currently best one is to define the pointer events on small devices. No perfect solution but usable. 

Scroll now does work again, search aswell. On mobile you have to click the radiobutton to select a DXCC.

Difference now:

DESKTOP:

<img width="577" alt="image" src="https://github.com/user-attachments/assets/acacfefa-4481-4ef4-9b84-52e8a44cd992">

MOBILE: 

<img width="352" alt="image" src="https://github.com/user-attachments/assets/d77739f5-8cf5-439e-aece-8c191fd89c24">

@phl0 Could you please test on a tablet? I currently do not have one available

2024-08-17 07:26 UTC, HB9HIL commented
@phl0 Could you please test on a tablet? I currently do not have one available

2024-08-20 18:35 UTC, phl0 requested changes
There is a problem with selecting None as DXCC. Results in a JS error because it is not contained in the DXCC list. https://github.com/HB9HIL/wavelog/pull/111 fixes this.

2024-08-20 18:41 UTC, phl0 commented
Oh sorry, forgot my initial feedback: Scrolling now works on a  mobile / tablet for me. Thanks for fixing this ;)

2024-08-20 18:51 UTC, phl0 approved these changes

2024-08-20 18:52 UTC, merged