[WIP]: Add page with distance records per SAT
wavelog/wavelog pull request #840
Opened 2024-08-29 15:15 UTC by phl0

2024-08-29 16:43 UTC, int2001 approved these changes
i like. works as designed ;)

2024-08-29 16:48 UTC, int2001 requested changes
Cosmetics (Formatting) and empty function

2024-08-29 16:48 UTC, int2001 commented on application/controllers/Distancerecords.php
> +    public function distancerecords() {
empty?

2024-08-29 16:48 UTC, int2001 commented on application/controllers/Distancerecords.php
> +    public function index()
Formatting (rest as well)? ;)

2024-08-29 22:36 UTC, phl0 commented on application/controllers/Distancerecords.php
> +    public function distancerecords() {
fixed.

2024-08-29 22:36 UTC, phl0 commented on application/controllers/Distancerecords.php
> +    public function index()
done.

2024-08-29 22:37 UTC, phl0 commented
Issues fixed. Aggree @int2001?

2024-08-30 05:04 UTC, int2001 approved these changes

2024-08-30 05:56 UTC, AndreasK79 approved these changes

2024-08-30 05:57 UTC, merged