Adding the ability to hide login button from visitors pages
wavelog/wavelog pull request #872
Opened 2024-09-04 03:00 UTC by desertblade

This resolves issue #846. Decided to add it to the appearance page, mimicking the Github button functionality.

2024-09-04 03:29 UTC, phl0 requested changes
Found two small things to change before we can accept this PR. 

But please also change it to be created against dev branch instead of master. Master branch is only used for stable code to release. All development happens in the dev branch.

2024-09-04 03:29 UTC, phl0 commented on application/controllers/Options.php
> +
Please remove this stray whitespace

2024-09-04 03:29 UTC, phl0 commented on application/views/options/appearance.php
> +                            <small id="publicLoginButtonHelp" class="form-text text-muted"><?= __("This enables the button to login to Wavelog in the public/vistors view"); ?></small>
Please correct typo here :) (->vistors)

2024-09-05 00:04 UTC, desertblade commented
Should be good to go. Its what I get by rushing.

2024-09-05 01:47 UTC, phl0 approved these changes
Fine now. So merge time 😇

2024-09-05 01:47 UTC, merged