[WIP]: Disable map click if modal is shown
wavelog/wavelog pull request #914
Opened 2024-09-09 11:31 UTC by phl0

Disabling cklick input upon showing the modal works. But re-enabling it is still an issue.

2024-09-13 14:30 UTC, HB9HIL requested changes

2024-09-13 14:30 UTC, HB9HIL commented on assets/js/leaflet/geocoding.js
> +	}
this is not necessary
```suggestion
	
```

2024-09-13 14:30 UTC, HB9HIL commented on assets/js/sections/gridmap.js
> +					$("#gridsquare_map").append(dialog.getModal());
change the id instead will fix the issue
```suggestion
					$("body").append(dialog.getModal());
```

2024-09-19 12:22 UTC, phl0 commented
Closing this in favor of https://github.com/wavelog/wavelog/pull/943 which is the better solution.

2024-09-19 12:22 UTC, closed without merging